# Generated by Django 5.0.6 on 2024-07-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_apiaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiaction',
            old_name='user',
            new_name='user_id',
        ),
    ]
