# Generated by Django 5.0.6 on 2024-07-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_rename_user_apiaction_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
